### ISSUE TITLE
checkset implementation

### ISSUE THREAD

**Issue by cll008** [sccn/get_chanlocs#5]
checkset at the end of the process can error and crash the plug-in without saving any results. Handle this better.

**Comment by jacobsen-noelle** [comment]
> checkset at the end of the process can error and crash the plug-in without saving any results. Handle this better.

I think this is because the fiducial locations are added to the end of EEG.chanlocs but does not match the number of channels. This causes a mismatch between expected number of channels (from EEG.nbchan) and those found in EEG.chanlocs (EEG.nbchan +3 fiducials)

**Comment by cll008** [comment]
Hi @jacobsen-noelle, have you experienced this issue? I tested it a few times on my end and eeg_checkchanlocs is behaving correctly (fiducials are moved to `EEG.chaninfo.nodatchans` and should not count against `nbchan`. 

Below is the log from my collaborator who reported this bug. Interestingly the crash happens after the `get_chanlocs` routine is completed with a complaint re: empty channel labels, which doesn't make much sense to me since `get_chanlocs` pulls from EEG.chanlocs and he completed the process and selected every electrode (after removing some channels. I tried to replicate this pipeline too but could not replicate the bug). Hm.

```
%%%%%%%%%%%%%%%%%%%%%%%
Saving reference .mat to C:\SCCN\paul\3D_Image\..\montageTemplate.mat
Moving electrode set 1 towards scalp by 7.50 mm...
Writing electrode locations to txt file...
Importing locations with readlocs()...
Deleting .txt file with electrode locations...
Electrode localization by get_chanlocs finished!
eeg_checkset warning: number of channels different in data and channel file/struct: channel file/struct removed
Warning: channel labels should not be empty, creating unique labels
Warning: the size of the channel location structure does not match with
         number of channels. Channel information have been removed.
%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by jacobsen-noelle** [comment]
Hi!

Yes, I experienced this same issue as well, which was really frustrating because it deleted the information I just labeled. I had to make a quick fix so that the fiducials were removed from the EEG.chanlocs structure, and I had a backup of the locations stored right after labeling was finished. I haven’t made an official change. The output text file is keeping the fiducial locations, and it’s reading back those locations in line 242 of get_chanlocs. I’m not sure why eeg_checkchanlocs() isn’t moving them like you expect it to. I can look into this issue more in the future and let you know if I find an official fix.

Best,
Noelle

From: Clement Lee ***@***.***>
Date: Thursday, May 13, 2021 at 1:40 PM
To: sccn/get_chanlocs ***@***.***>
Cc: Jacobsen,Noelle A ***@***.***>, Mention ***@***.***>
Subject: Re: [sccn/get_chanlocs] checkset implementation (#5)
[External Email]


Hi @jacobsen-noelle<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jacobsen-2Dnoelle&d=DwMCaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=D6vo-sTwTKQ4CnETni9CUC32PkfvCsmxJRnYG2rwADQ&m=UkCCywaKpoyMLduWkBbM7fJTor_mNwMUD15IxjdMCsg&s=7-xCXNPCQUI4CljZBITkGtF0FateH4qXIo5wXGvs2Yg&e=>, have you experienced this issue? I tested it a few times on my end and eeg_checkchanlocs is behaving correctly (fiducials are moved to EEG.chaninfo.nodatchans and should not count against nbchan.

Below is the log from my collaborator who reported this bug. Interestingly the crash happens after the get_chanlocs routine is completed with a complaint re: empty channel labels, which doesn't make much sense to me since get_chanlocs pulls from EEG.chanlocs and he completed the process and selected every electrode. Hm.



%%%%%%%%%%%%%%%%%%%%%%%

Saving reference .mat to C:\SCCN\paul\3D_Image\..\montageTemplate.mat

Moving electrode set 1 towards scalp by 7.50 mm...

Writing electrode locations to txt file...

Importing locations with readlocs()...

Deleting .txt file with electrode locations...

Electrode localization by get_chanlocs finished!

eeg_checkset warning: number of channels different in data and channel file/struct: channel file/struct removed

Warning: channel labels should not be empty, creating unique labels

Warning: the size of the channel location structure does not match with

         number of channels. Channel information have been removed.

%%%%%%%%%%%%%%%%%%%%%%%

**Comment by cll008** [comment]
Thanks Noelle. I understand how frustrating that must feel... something similar happened to me multiple times while developing the plug-in 😅
One follow up question: what EEGLAB version are you using?

**Comment by jacobsen-noelle** [comment]
Well I’m very appreciative of all of you who work on developing these tools. I’m using version 14.

________________________________

**Comment by cll008** [comment]
User feedback is invaluable too so thank you for going above and beyond on your end. You've helped me pin down the issue: older EEGLAB versions don't recognize LHJ|LHT|RHJ|RHT as fiducials so those are not counted as `nodatchans`. I'll add a version checker and a warning at the beginning of the plug-in.
